export const APPOINTMENT_SLOTS_REQUEST = "APPOINTMENT_SLOTS_REQUEST";
export const APPOINTMENT_SLOTS_SUCCESS = "APPOINTMENT_SLOTS_SUCCESS";
export const APPOINTMENT_SLOTS_FAIL = "APPOINTMENT_SLOTS_FAIL";

export const APPOINTMENT_SLOT_CREATE_REQUEST = "APPOINTMENT_SLOT_CREATE_REQUEST";
export const APPOINTMENT_SLOT_CREATE_SUCCESS = "APPOINTMENT_SLOT_CREATE_SUCCESS";
export const APPOINTMENT_SLOT_CREATE_FAIL = "APPOINTMENT_SLOT_CREATE_FAIL";
export const APPOINTMENT_SLOT_CREATE_RESET = "APPOINTMENT_SLOT_CREATE_RESET";

export const APPOINTMENT_SLOT_UPDATE_REQUEST = "APPOINTMENT_SLOT_UPDATE_REQUEST";
export const APPOINTMENT_SLOT_UPDATE_SUCCESS = "APPOINTMENT_SLOT_UPDATE_SUCCESS";
export const APPOINTMENT_SLOT_UPDATE_FAIL = "APPOINTMENT_SLOT_UPDATE_FAIL";
export const APPOINTMENT_SLOT_UPDATE_RESET = "APPOINTMENT_SLOT_UPDATE_RESET";

export const APPOINTMENT_SLOT_DELETE_REQUEST = "APPOINTMENT_SLOT_DELETE_REQUEST";
export const APPOINTMENT_SLOT_DELETE_SUCCESS = "APPOINTMENT_SLOT_DELETE_SUCCESS";
export const APPOINTMENT_SLOT_DELETE_FAIL = "APPOINTMENT_SLOT_DELETE_FAIL";
export const APPOINTMENT_SLOT_DELETE_RESET = "APPOINTMENT_SLOT_DELETE_RESET";

export const APPOINTMENT_SLOT_ASSIGN_REQUEST = "APPOINTMENT_SLOT_ASSIGN_REQUEST";
export const APPOINTMENT_SLOT_ASSIGN_SUCCESS = "APPOINTMENT_SLOT_ASSIGN_SUCCESS";
export const APPOINTMENT_SLOT_ASSIGN_FAIL = "APPOINTMENT_SLOT_ASSIGN_FAIL";
export const APPOINTMENT_SLOT_ASSIGN_RESET = "APPOINTMENT_SLOT_ASSIGN_RESET";


// New Book Direct Appointment Actions
export const BOOK_DIRECT_APPOINTMENT_REQUEST = 'BOOK_DIRECT_APPOINTMENT_REQUEST';
export const BOOK_DIRECT_APPOINTMENT_SUCCESS = 'BOOK_DIRECT_APPOINTMENT_SUCCESS';
export const BOOK_DIRECT_APPOINTMENT_FAILURE = 'BOOK_DIRECT_APPOINTMENT_FAILURE';
export const BOOK_DIRECT_APPOINTMENT_RESET = 'BOOK_DIRECT_APPOINTMENT_RESET';

// Guest Appointment with Registration Actions
export const BOOK_GUEST_APPOINTMENT_REQUEST = 'BOOK_GUEST_APPOINTMENT_REQUEST';
export const BOOK_GUEST_APPOINTMENT_SUCCESS = 'BOOK_GUEST_APPOINTMENT_SUCCESS';
export const BOOK_GUEST_APPOINTMENT_FAILURE = 'BOOK_GUEST_APPOINTMENT_FAILURE';
export const BOOK_GUEST_APPOINTMENT_RESET = 'BOOK_GUEST_APPOINTMENT_RESET';

// User appointments actions
export const USER_APPOINTMENTS_REQUEST = 'USER_APPOINTMENTS_REQUEST';
export const USER_APPOINTMENTS_SUCCESS = 'USER_APPOINTMENTS_SUCCESS';
export const USER_APPOINTMENTS_FAIL = 'USER_APPOINTMENTS_FAIL';

// Admin appointments management actions
export const ADMIN_PREVIOUS_APPOINTMENTS_REQUEST = 'ADMIN_PREVIOUS_APPOINTMENTS_REQUEST';
export const ADMIN_PREVIOUS_APPOINTMENTS_SUCCESS = 'ADMIN_PREVIOUS_APPOINTMENTS_SUCCESS';
export const ADMIN_PREVIOUS_APPOINTMENTS_FAIL = 'ADMIN_PREVIOUS_APPOINTMENTS_FAIL';

export const ADMIN_UPCOMING_APPOINTMENTS_REQUEST = 'ADMIN_UPCOMING_APPOINTMENTS_REQUEST';
export const ADMIN_UPCOMING_APPOINTMENTS_SUCCESS = 'ADMIN_UPCOMING_APPOINTMENTS_SUCCESS';
export const ADMIN_UPCOMING_APPOINTMENTS_FAIL = 'ADMIN_UPCOMING_APPOINTMENTS_FAIL';

export const ADMIN_APPOINTMENT_STATUS_UPDATE_REQUEST = 'ADMIN_APPOINTMENT_STATUS_UPDATE_REQUEST';
export const ADMIN_APPOINTMENT_STATUS_UPDATE_SUCCESS = 'ADMIN_APPOINTMENT_STATUS_UPDATE_SUCCESS';
export const ADMIN_APPOINTMENT_STATUS_UPDATE_FAIL = 'ADMIN_APPOINTMENT_STATUS_UPDATE_FAIL';

export const ADMIN_APPOINTMENT_CANCEL_REQUEST = 'ADMIN_APPOINTMENT_CANCEL_REQUEST';
export const ADMIN_APPOINTMENT_CANCEL_SUCCESS = 'ADMIN_APPOINTMENT_CANCEL_SUCCESS';
export const ADMIN_APPOINTMENT_CANCEL_FAIL = 'ADMIN_APPOINTMENT_CANCEL_FAIL';
export const ADMIN_APPOINTMENT_CANCEL_RESET = 'ADMIN_APPOINTMENT_CANCEL_RESET';

// Instructor constants
export const INSTRUCTORS_REQUEST = "INSTRUCTORS_REQUEST";
export const INSTRUCTORS_SUCCESS = "INSTRUCTORS_SUCCESS";
export const INSTRUCTORS_FAIL = "INSTRUCTORS_FAIL";
export const INSTRUCTORS_RESET = "INSTRUCTORS_RESET";