export const APPOINTMENT_SLOTS_REQUEST = "APPOINTMENT_SLOTS_REQUEST";
export const APPOINTMENT_SLOTS_SUCCESS = "APPOINTMENT_SLOTS_SUCCESS";
export const APPOINTMENT_SLOTS_FAIL = "APPOINTMENT_SLOTS_FAIL";

export const APPOINTMENT_SLOT_CREATE_REQUEST = "APPOINTMENT_SLOT_CREATE_REQUEST";
export const APPOINTMENT_SLOT_CREATE_SUCCESS = "APPOINTMENT_SLOT_CREATE_SUCCESS";
export const APPOINTMENT_SLOT_CREATE_FAIL = "APPOINTMENT_SLOT_CREATE_FAIL";
export const APPOINTMENT_SLOT_CREATE_RESET = "APPOINTMENT_SLOT_CREATE_RESET";

export const APPOINTMENT_SLOT_UPDATE_REQUEST = "APPOINTMENT_SLOT_UPDATE_REQUEST";
export const APPOINTMENT_SLOT_UPDATE_SUCCESS = "APPOINTMENT_SLOT_UPDATE_SUCCESS";
export const APPOINTMENT_SLOT_UPDATE_FAIL = "APPOINTMENT_SLOT_UPDATE_FAIL";
export const APPOINTMENT_SLOT_UPDATE_RESET = "APPOINTMENT_SLOT_UPDATE_RESET";

export const APPOINTMENT_SLOT_DELETE_REQUEST = "APPOINTMENT_SLOT_DELETE_REQUEST";
export const APPOINTMENT_SLOT_DELETE_SUCCESS = "APPOINTMENT_SLOT_DELETE_SUCCESS";
export const APPOINTMENT_SLOT_DELETE_FAIL = "APPOINTMENT_SLOT_DELETE_FAIL";
export const APPOINTMENT_SLOT_DELETE_RESET = "APPOINTMENT_SLOT_DELETE_RESET";


// New Book Direct Appointment Actions
export const BOOK_DIRECT_APPOINTMENT_REQUEST = 'BOOK_DIRECT_APPOINTMENT_REQUEST';
export const BOOK_DIRECT_APPOINTMENT_SUCCESS = 'BOOK_DIRECT_APPOINTMENT_SUCCESS';
export const BOOK_DIRECT_APPOINTMENT_FAILURE = 'BOOK_DIRECT_APPOINTMENT_FAILURE';
export const BOOK_DIRECT_APPOINTMENT_RESET = 'BOOK_DIRECT_APPOINTMENT_RESET';