export const GUEST_COURSE_LIST_REQUEST = "GUEST_COURSE_LIST_REQUEST";
export const GUEST_COURSE_LIST_SUCCESS = "GUEST_COURSE_LIST_SUCCESS";
export const GUEST_COURSE_LIST_FAIL = "GUEST_COURSE_LIST_FAIL";

export const GUEST_COURSE_DETAIL_REQUEST = "GUEST_COURSE_DETAIL_REQUEST";
export const GUEST_COURSE_DETAIL_SUCCESS = "GUEST_COURSE_DETAIL_SUCCESS";
export const GUEST_COURSE_DETAIL_FAIL = "GUEST_COURSE_DETAIL_FAIL";

export const ENROLL_COURSE_REQUEST = "ENROLL_COURSE_REQUEST";
export const ENROLL_COURSE_SUCCESS = "ENROLL_COURSE_SUCCESS";
export const ENROLL_COURSE_FAIL = "ENROLL_COURSE_FAIL";