export const COURSE_REVIEW_LIST_REQUEST = "COURSE_REVIEW_LIST_REQUEST";
export const COURSE_REVIEW_LIST_SUCCESS = "COURSE_REVIEW_LIST_SUCCESS";
export const COURSE_REVIEW_LIST_FAIL = "COURSE_REVIEW_LIST_FAIL";

export const COURSE_REVIEW_CREATE_REQUEST = "COURSE_REVIEW_CREATE_REQUEST";
export const COURSE_REVIEW_CREATE_SUCCESS = "COURSE_REVIEW_CREATE_SUCCESS";
export const COURSE_REVIEW_CREATE_FAIL = "COURSE_REVIEW_CREATE_FAIL";

export const COURSE_REVIEW_UPDATE_REQUEST = "COURSE_REVIEW_UPDATE_REQUEST";
export const COURSE_REVIEW_UPDATE_SUCCESS = "COURSE_REVIEW_UPDATE_SUCCESS";
export const COURSE_REVIEW_UPDATE_FAIL = "COURSE_REVIEW_UPDATE_FAIL";

export const COURSE_REVIEW_DELETE_REQUEST = "COURSE_REVIEW_DELETE_REQUEST";
export const COURSE_REVIEW_DELETE_SUCCESS = "COURSE_REVIEW_DELETE_SUCCESS";
export const COURSE_REVIEW_DELETE_FAIL = "COURSE_REVIEW_DELETE_FAIL";

