export const USER_COURSE_LIST_REQUEST = "USER_COURSE_LIST_REQUEST";
export const USER_COURSE_LIST_SUCCESS = "USER_COURSE_LIST_SUCCESS";
export const USER_COURSE_LIST_FAIL = "USER_COURSE_LIST_FAIL"; 
export const USER_COURSE_ADD = "USER_COURSE_ADD";

export const USER_COURSE_DETAILS_REQUEST = "USER_COURSE_DETAILS_REQUEST";
export const USER_COURSE_DETAILS_SUCCESS = "USER_COURSE_DETAILS_SUCCESS";
export const USER_COURSE_DETAILS_FAIL = "USER_COURSE_DETAILS_FAIL";